import type { Product } from "@/components/ProductCard";
import type { BlogPost } from "@/components/BlogCard";

// ─── Local image paths (served from /public/assets/images/products/) ──────────
const IMG = {
  faceWash:   "/assets/images/products/face-wash.jpg",
  serum:      "/assets/images/products/serum.jpg",
  sunscreen:  "/assets/images/products/sunscreen.jpg",
  faceMask:   "/assets/images/products/face-mask.jpg",
  bodyLotion: "/assets/images/products/body-lotion.jpg",
  bodyButter: "/assets/images/products/body-butter.jpg",
  bodyWash:   "/assets/images/products/body-wash.jpg",
  bodyScrub:  "/assets/images/products/body-scrub.jpg",
  hairOil:    "/assets/images/products/hair-oil.jpg",
  shampoo:    "/assets/images/products/shampoo.jpg",
  conditioner:"/assets/images/products/conditioner.jpg",
  hairMask:   "/assets/images/products/hair-mask.jpg",
  hairSerum:  "/assets/images/products/hair-serum.jpg",
  kajal:      "/assets/images/products/kajal.jpg",
  lip:        "/assets/images/products/lip.jpg",
  fragrance:  "/assets/images/products/fragrance.jpg",
  giftSet:    "/assets/images/products/gift-set.jpg",

  // TWC
  twcCoffeeScrub:      "/assets/images/products/real/twc-coffee-body-scrub.jpg",
  twcSkinBrightening:  "/assets/images/products/real/twc-skin-brightening-cream.jpg",
  twcLipScrub:         "/assets/images/products/real/twc-lip-lightening-scrub.jpg",
  twcUnderEye:         "/assets/images/products/real/twc-under-eye-cream.jpg",
  twcDeo:              "/assets/images/products/real/twc-deodorant-lightening-roll-on.jpg",
  twcVibeTribe:        "/assets/images/products/real/twc-vibe-tribe.jpg",
  twcBawsy:            "/assets/images/products/real/twc-eau-de-parfum-bawsy.jpg",
  twcClassy:           "/assets/images/products/real/twc-eau-de-parfum-classy.jpg",
  twcGutsy:            "/assets/images/products/real/twc-eau-de-parfum-gutsy.jpg",
  twcSassy:            "/assets/images/products/real/twc-eau-de-parfum-sassy.jpg",

  // Kimirica
  kimLoveLotion:       "/assets/images/products/real/kim-love-story-body-lotion.jpg",
  kimVivahCream:       "/assets/images/products/real/kim-vivah-turmeric-body-cream.jpg",
  kimFiveLotion:       "/assets/images/products/real/kim-five-elements-body-lotion.jpg",
  kimHerbalistLotion:  "/assets/images/products/real/kim-the-herbalist-body-lotion.jpg",
  kimEarthLotion:      "/assets/images/products/real/kim-earth-body-lotion.jpg",
  kimFrenchLotion:     "/assets/images/products/real/kim-the-french-note-body-lotion.jpg",
  kimSouqWash:         "/assets/images/products/real/kim-the-souq-hand-body-wash.jpg",
  kimAmalfiWash:       "/assets/images/products/real/kim-bella-amalfi-hand-body-wash.jpg",
  kimSilverDuo:        "/assets/images/products/real/kim-lady-in-silver-bath-body-duo.jpg",
  kimMidnightDuo:      "/assets/images/products/real/kim-midnight-masquerade-bath-body-duo.jpg",

  // Mamaearth
  maeVitCFw:           "/assets/images/products/real/mae-vitamin-c-face-wash.jpg",
  maeUbtanFw:          "/assets/images/products/real/mae-ubtan-face-wash.jpg",
  maeRiceFw:           "/assets/images/products/real/mae-rice-face-wash.jpg",
  maeTeaTreeFw:        "/assets/images/products/real/mae-tea-tree-face-wash.jpg",
  maeOnionOil:         "/assets/images/products/real/mae-onion-hair-oil.jpg",
  maeOnionShp:         "/assets/images/products/real/mae-onion-shampoo.jpg",
  maeVitCLotion:       "/assets/images/products/real/mae-vitamin-c-body-lotion.jpg",
  maeUbtanWash:        "/assets/images/products/real/mae-ubtan-body-wash.jpg",
};

export const BRANDS = ["The Woman Company", "Kimirica", "Mamaearth"] as const;
export type Brand = (typeof BRANDS)[number];

export const CATEGORIES = [
  "Face",
  "Face Wash",
  "Face Serum",
  "Sunscreen",
  "Face Mask",
  "Fragrance",
  "Body",
  "Body Lotion",
  "Body Cream",
  "Body Wash",
  "Body Mist",
  "Hair Care",
  "Makeup",
  "Duos",
] as const;
export type Category = (typeof CATEGORIES)[number];

const inr = (n: number) => `₹${n}`;

const p = (
  id: string,
  name: string,
  price: number,
  brand: string,
  category: Category,
  image: string,
  variant?: string,
  tag?: string,
  description?: string,
  rating = 4.3,
  stock = 24,
): Product => ({
  id, name, price, priceLabel: inr(price), brand,
  category, image, variant, tag, description, rating, stock,
});

export const products: Product[] = [
  // ── The Woman Company — Face ──────────────────────────────────────────────
  p("twc-lip-scrub",   "Lip Lightening Scrub",         399,  "The Woman Company", "Face",      IMG.twcLipScrub,      "Sugar & Rose",
    undefined,
    "A gentle exfoliating lip scrub with sugar crystals and rose extract that removes dead skin, fades pigmentation, and leaves lips soft, smooth, and naturally pink.",
    4.4, 30),
  p("twc-skin-bright", "Skin Brightening Cream",       599,  "The Woman Company", "Face",      IMG.twcSkinBrightening,      "Vitamin C",
    "Bestseller",
    "Powered by stabilised Vitamin C, this lightweight brightening cream reduces dark spots and uneven tone, boosting radiance with every use. Dermatologist tested.",
    4.6, 18),
  p("twc-under-eye",   "Under Eye Cream",              549,  "The Woman Company", "Face",      IMG.twcUnderEye,      "Caffeine & Cucumber",
    undefined,
    "A targeted under-eye cream with caffeine to reduce puffiness and cucumber extract to soothe dark circles, leaving the delicate eye area visibly refreshed.",
    4.2, 22),

  // ── The Woman Company — Fragrance ─────────────────────────────────────────
  p("twc-edp-bawsy",   "EDP Bawsy",                   999,  "The Woman Company", "Fragrance", IMG.twcBawsy,  "Eau de Parfum 50ml",
    undefined,
    "A bold, unapologetic floral-woody fragrance for the woman who walks into a room and owns it. Top notes of bergamot, heart of jasmine, base of sandalwood.",
    4.5, 12),
  p("twc-edp-classy",  "EDP Classy",                  999,  "The Woman Company", "Fragrance", IMG.twcClassy,  "Eau de Parfum 50ml",
    undefined,
    "Timeless elegance in a bottle. A soft powdery floral with notes of rose, iris, and white musk for the woman who leads with grace.",
    4.7, 15),
  p("twc-edp-gutsy",   "EDP Gutsy",                   999,  "The Woman Company", "Fragrance", IMG.twcGutsy,  "Eau de Parfum 50ml",
    undefined,
    "A daring oriental-floral that blends oud, amber, and tuberose. For the woman who defies expectations and redefines norms.",
    4.3, 10),
  p("twc-edp-sassy",   "EDP Sassy",                   999,  "The Woman Company", "Fragrance", IMG.twcSassy,  "Eau de Parfum 50ml",
    undefined,
    "A playful, citrus-floral burst of confidence. Notes of grapefruit, peony, and cedarwood for the free-spirited modern woman.",
    4.4, 14),
  p("twc-vibe-tribe",  "Vibe Tribe Gift Set",         2499, "The Woman Company", "Fragrance", IMG.twcVibeTribe,    "4-piece EDP set",
    "Gift",
    "Four iconic fragrances — Bawsy, Classy, Gutsy & Sassy — curated in a premium gift box. The perfect celebration of womanhood for every occasion.",
    4.8, 8),

  // ── The Woman Company — Body ──────────────────────────────────────────────
  p("twc-coffee-scrub","Coffee Body Scrub",            449,  "The Woman Company", "Body",      IMG.twcCoffeeScrub,  "Coffee & Cocoa",
    undefined,
    "A rich exfoliating scrub that buffs away dead skin with finely ground coffee, leaving your body smoother, firmer, and with a natural healthy glow.",
    4.3, 25),
  p("twc-deo-rollon",  "Deodorant Lightening Roll On",299,  "The Woman Company", "Body",      IMG.twcDeo, "Aluminium-free",
    undefined,
    "An aluminium-free roll-on deodorant that provides 24-hour freshness while gently lightening the underarm area with niacinamide and kojic acid.",
    4.1, 35),

  // ── Kimirica — Body Lotions ───────────────────────────────────────────────
  p("kim-love-lotion",       "Love Story Body Lotion",              449, "Kimirica", "Body Lotion", IMG.kimLoveLotion, "Jasmine & Gardenia",
    undefined, "A dreamy floral lotion that deeply hydrates with jasmine and gardenia extracts. Absorbs quickly for silky, fragrant skin all day.", 4.5, 20),
  p("kim-five-lotion",       "Five Elements Body Lotion 300ml",     337, "Kimirica", "Body Lotion", IMG.kimFiveLotion, "Mimosa & Orange",
    undefined, "Inspired by the five elements of nature, this lotion balances your skin with energising mimosa and vitamin-rich orange peel extract.", 4.3, 22),
  p("kim-french-lotion",     "French Note Hand & Body Lotion",      449, "Kimirica", "Body Lotion", IMG.kimFrenchLotion, "French Lavender",
    undefined, "Transport yourself to Provence with this luxurious lavender-infused lotion that calms, nourishes and leaves skin beautifully scented.", 4.6, 18),
  p("kim-earth-lotion",      "Earth Body Lotion",                   337, "Kimirica", "Body Lotion", IMG.kimEarthLotion, "Persian Sweet Lime",
    undefined, "Grounded in nature, this lotion uses Persian sweet lime and earth minerals to restore moisture and radiance to everyday skin.", 4.2, 28),
  p("kim-herbalist-lotion",  "Herbalist Body Lotion",               449, "Kimirica", "Body Lotion", IMG.kimHerbalistLotion, "Bergamot & Patchouli",
    undefined, "An aromatic herbal blend of bergamot and patchouli deeply conditions skin while releasing a grounding, sophisticated scent.", 4.4, 16),
  p("kim-vivah-lotion",      "Vivah Body Lotion 300ml",             487, "Kimirica", "Body Lotion", IMG.kimVivahCream, "Marigold & Turmeric",
    undefined, "Infused with marigold and turmeric — traditional Indian wedding botanicals — this lotion brightens and nourishes for a radiant bridal glow.", 4.7, 12),
  p("kim-gulistan-lotion",   "The Gulistan Hand & Body Lotion",     487, "Kimirica", "Body Lotion", IMG.bodyLotion, "Rose Absolute & Iris",
    undefined, "Inspired by Persian rose gardens, this velvety lotion combines rose absolute and iris for deep hydration and a romantic floral trail.", 4.5, 14),
  p("kim-apothecary-lotion", "Indian Apothecary Hand & Body Lotion",449, "Kimirica", "Body Lotion", IMG.bodyLotion, "Ashwagandha",
    undefined, "Rooted in Ayurveda, this adaptogen-rich lotion with ashwagandha replenishes stressed skin and restores its natural vitality.", 4.3, 18),
  p("kim-pharma-lotion",     "Pharmacopia Body Lotion 250ml",       412, "Kimirica", "Body Lotion", IMG.bodyLotion, "Argan Oil",
    undefined, "A clinical-grade moisturiser with Moroccan argan oil that repairs the skin barrier, reduces dryness and improves elasticity.", 4.4, 20),
  p("kim-ignis-lotion",      "Ignis Body Lotion 300ml",             224, "Kimirica", "Body Lotion", IMG.bodyLotion, "Bergamot & Tea Tree",
    undefined, "A lightweight, cooling lotion with bergamot and tea tree that refreshes summer skin while providing lasting moisture.", 4.1, 30),

  // ── Kimirica — Body Creams ────────────────────────────────────────────────
  p("kim-vivah-cream",     "Vivah Body Cream 100gm",               674, "Kimirica", "Body Cream", IMG.kimVivahCream, "Marigold & Turmeric",
    undefined, "A rich, indulgent body cream with marigold and turmeric for intense overnight nourishment and a luminous morning glow.", 4.6, 10),
  p("kim-gentleman-cream", "The Gentleman Niacinamide Body Cream", 449, "Kimirica", "Body Cream", IMG.bodyButter, "Musk & Amber",
    undefined, "Niacinamide-powered body cream that fades body acne, evens skin tone and hydrates deeply with a warm, sophisticated musk scent.", 4.3, 15),
  p("kim-french-cream",    "The French Note Body Cream 100gm",     674, "Kimirica", "Body Cream", IMG.bodyButter, "French Lavender",
    undefined, "A decadent French lavender body cream with shea butter and jojoba that melts into skin overnight for morning-fresh softness.", 4.5, 12),
  p("kim-gulistan-cream",  "The Gulistan Body Cream 100gm",        637, "Kimirica", "Body Cream", IMG.bodyButter, "Rose Absolute & Iris",
    undefined, "An opulent body cream inspired by Mughal rose gardens, loaded with rose absolute and iris for petal-soft, luminous skin.", 4.7, 8),

  // ── Kimirica — Body Washes ────────────────────────────────────────────────
  p("kim-apothecary-wash",  "Indian Apothecary Body Wash",         374, "Kimirica", "Body Wash", IMG.bodyWash, "Ashwagandha",
    undefined, "An Ayurvedic body wash with ashwagandha and holy basil that cleanses deeply while balancing stressed, sensitive skin.", 4.4, 22),
  p("kim-atw-moist-wash",   "Around The World Moisturizing Body Wash", 337, "Kimirica", "Body Wash", IMG.bodyWash, "Vanilla & Coconut",
    undefined, "A creamy, tropical body wash with coconut milk and Madagascar vanilla that lathers richly and leaves skin moisturised.", 4.3, 28),
  p("kim-atw-clarify-wash", "Around The World Clarifying Body Wash",   337, "Kimirica", "Body Wash", IMG.bodyWash, "Plum & Violet",
    undefined, "A refreshing clarifying body wash with plum extract and violet that removes impurities while preserving the skin's natural moisture.", 4.2, 24),
  p("kim-atw-renew-wash",   "Around The World Renewing Body Wash",     337, "Kimirica", "Body Wash", IMG.bodyWash, "Rose & Peach",
    undefined, "A regenerating body wash with rose hip and peach extract that gently exfoliates and renews dull, tired skin.", 4.4, 20),
  p("kim-souq-wash",        "The Souq Body & Hand Wash",               524, "Kimirica", "Body Wash", IMG.kimSouqWash, "Saffron & Sandalwood",
    undefined, "Inspired by Middle Eastern souqs, this luxurious wash combines saffron and sandalwood for an intensely nourishing cleanse.", 4.6, 15),
  p("kim-fig-wash",         "Figure It Out Body & Hand Wash",          524, "Kimirica", "Body Wash", IMG.bodyWash, "Fig & Cedar",
    undefined, "A sophisticated wash with Mediterranean fig and atlas cedar that cleanses, tones and leaves a subtle woody-fruity scent.", 4.3, 18),
  p("kim-amalfi-wash",      "Bella Amalfi Body & Hand Wash",           524, "Kimirica", "Body Wash", IMG.kimAmalfiWash, "Sea Water & Vetiver",
    undefined, "Evoking the Italian Amalfi coast, this wash with sea water minerals and vetiver root deeply cleanses while mineralising skin.", 4.5, 16),

  // ── Kimirica — Body Mists ─────────────────────────────────────────────────
  p("kim-mist-plum",    "Around The World Body Mist", 337, "Kimirica", "Body Mist", IMG.fragrance, "Plum & Violet",
    undefined, "A refreshing plum and violet mist that hydrates skin between washes and leaves a light, lasting fragrance.", 4.2, 30),
  p("kim-mist-rose",    "Around The World Body Mist", 337, "Kimirica", "Body Mist", IMG.fragrance, "Rose & Peach",
    undefined, "A delicate rose and peach body mist for an all-day floral freshness that uplifts your mood with every spritz.", 4.4, 28),
  p("kim-mist-vanilla", "Around The World Body Mist", 337, "Kimirica", "Body Mist", IMG.fragrance, "Vanilla & Coconut",
    undefined, "A warm, comforting vanilla-coconut mist that envelops you in tropical softness and a subtle sweet trail.", 4.3, 32),
  p("kim-love-yogurt",  "Love Story Body Yogurt",    449, "Kimirica", "Body Mist",  IMG.kimLoveLotion, "Jasmine & Gardenia",
    undefined, "A whipped yogurt-textured body cream mist that provides instant cooling relief while delivering jasmine-scented deep hydration.", 4.5, 20),

  // ── Kimirica — Duos / Sets ────────────────────────────────────────────────
  p("kim-silver-duo",     "Lady In Silver Bath & Body Duo",          524, "Kimirica", "Duos", IMG.kimSilverDuo, "White Wisteria",
    undefined, "An elegant duo of body wash and lotion in the coveted White Wisteria scent — perfect as a gift or self-care treat.", 4.5, 10),
  p("kim-midnight-duo",   "Midnight Masquerade Bath & Body Duo",     524, "Kimirica", "Duos", IMG.kimMidnightDuo, "Neroli & Thyme",
    undefined, "A mysterious, sensual duo of body wash and lotion with neroli and thyme for an unforgettable bedtime ritual.", 4.4, 12),
  p("kim-love-duo",       "Love Story Body Wash & Lotion Duo",       786, "Kimirica", "Duos", IMG.giftSet, "Jasmine & Gardenia",
    undefined, "The iconic Love Story duo — body wash and lotion in one gift-ready set for floral, romantic skincare.", 4.7, 8),
  p("kim-earth-duo",      "Earth Shower Gel & Body Lotion Duo",      636, "Kimirica", "Duos", IMG.giftSet, "Persian Sweet Lime",
    undefined, "A citrus-forward duo inspired by the earth's natural vitality, combining a refreshing shower gel with a hydrating lotion.", 4.3, 14),
  p("kim-five-duo",       "Five Elements Body Care Duo",             636, "Kimirica", "Duos", IMG.giftSet, "Mimosa & Orange",
    undefined, "A balanced body care duo rooted in the harmony of nature's five elements for restored, radiant skin.", 4.4, 12),
  p("kim-herbalist-duo",  "Herbalist Body Care Duo",                 824, "Kimirica", "Duos", IMG.giftSet, "Bergamot & Patchouli",
    undefined, "A herbalist's gift to your skin — a grounding bergamot-patchouli duo of shower gel and body lotion.", 4.5, 10),
  p("kim-gulistan-duo",   "The Gulistan Shower Gel & Lotion Duo",    861, "Kimirica", "Duos", IMG.giftSet, "Rose Absolute & Iris",
    undefined, "The ultimate floral indulgence — a luxurious rose and iris duo wrapped in Persian-inspired packaging.", 4.7, 6),
  p("kim-apothecary-duo", "Indian Apothecary Body Care Duo",         824, "Kimirica", "Duos", IMG.giftSet, "Ashwagandha",
    undefined, "Ayurvedic goodness in a duo — body wash and lotion with adaptogenic ashwagandha for rejuvenated, balanced skin.", 4.4, 10),
  p("kim-french-duo",     "The French Note Body Care Duo",           974, "Kimirica", "Duos", IMG.giftSet, "French Lavender",
    undefined, "A Parisian-inspired premium duo with French lavender for the ultimate luxury bath and body ritual.", 4.8, 5),
  p("kim-gentleman-duo",  "The Gentleman Body Wash & Lotion Duo",    674, "Kimirica", "Duos", IMG.giftSet, "Musk & Amber",
    undefined, "An effortlessly sophisticated duo with musk and amber — a complete body care ritual in a curated gift set.", 4.5, 9),
  p("kim-atw-mist-set",   "Around The World Body Mist Gift Set",     899, "Kimirica", "Duos", IMG.giftSet, "3-in-1",
    undefined, "Three Around The World body mists — Plum & Violet, Rose & Peach, Vanilla & Coconut — in an elegant gift box.", 4.6, 8),

  // ── Mamaearth — Face Wash ─────────────────────────────────────────────────
  p("mae-fw-vitc",    "Vitamin C Face Wash",      249, "Mamaearth", "Face Wash", IMG.maeVitCFw, "Vitamin C & Turmeric",
    "Bestseller",
    "A brightening face wash with 1% Vitamin C and turmeric extract that removes dullness, reduces dark spots and gives you a luminous, glass-skin glow. Free from sulphates and parabens.",
    4.5, 40),
  p("mae-fw-ubtan",   "Ubtan Face Wash",          249, "Mamaearth", "Face Wash", IMG.maeUbtanFw, "Turmeric & Saffron",
    "Toxin-Free ✓",
    "Inspired by ancient Indian beauty rituals, this ubtan face wash with turmeric and saffron naturally brightens skin tone and removes tan for a healthy, golden glow.",
    4.4, 38),
  p("mae-fw-rice",    "Rice Face Wash",           249, "Mamaearth", "Face Wash", IMG.maeRiceFw, "Rice Water & Niacinamide",
    "New",
    "A K-beauty inspired face wash with rice water and niacinamide that minimises pores, evens skin tone and gives a refined, translucent complexion.",
    4.3, 42),
  p("mae-fw-teatree", "Tea Tree Face Wash",       249, "Mamaearth", "Face Wash", IMG.maeTeaTreeFw, "Tea Tree & Salicylic Acid",
    "Toxin-Free ✓",
    "A powerful acne-fighting face wash with tea tree oil and salicylic acid that deep-cleanses pores, reduces breakouts and controls excess oil without over-drying.",
    4.5, 36),
  p("mae-fw-multani", "Multani Mitti Face Wash",  249, "Mamaearth", "Face Wash", IMG.faceWash, "Multani Mitti & Rose",
    "Toxin-Free ✓",
    "A gentle clay-based face wash with multani mitti (Fuller's Earth) and rose water that absorbs excess sebum, shrinks pores and leaves skin matte and fresh.",
    4.2, 44),

  // ── Mamaearth — Face Serum & Cream ───────────────────────────────────────
  p("mae-ser-vitc",      "Vitamin C Daily Glow Face Serum",  599, "Mamaearth", "Face Serum", IMG.serum, "Vitamin C",
    "Toxin-Free ✓",
    "A potent daily serum with 10% stabilised Vitamin C that visibly reduces pigmentation, brightens skin and defends against free radicals for a healthy, lasting glow.",
    4.6, 28),
  p("mae-cr-illuminate", "Skin Illuminate Face Cream",       349, "Mamaearth", "Face Serum", IMG.serum, "Skin Brightening",
    "Toxin-Free ✓",
    "A lightweight brightening moisturiser with daisy flower extract and niacinamide that reduces melanin production for a visibly even, radiant skin tone.",
    4.3, 32),
  p("mae-cr-blemish",    "Bye Bye Blemishes Face Cream",     349, "Mamaearth", "Face Serum", IMG.serum, "Blemish Control",
    "Toxin-Free ✓",
    "A targeted blemish cream with white peony extract and bearberry that fades dark spots, acne marks and post-inflammatory hyperpigmentation over time.",
    4.4, 30),
  p("mae-cr-undereye",   "Under Eye Cream",                  299, "Mamaearth", "Face Serum", IMG.serum, "Cucumber & Peptides",
    "Toxin-Free ✓",
    "A refreshing under-eye cream with cucumber and tripeptide-5 that reduces puffiness, minimises dark circles and firms the delicate eye contour.",
    4.2, 34),
  p("mae-gel-aloe",      "Aloe Vera Gel 100% Pure",          249, "Mamaearth", "Face Serum", IMG.serum, "100% Pure Aloe",
    "Toxin-Free ✓",
    "100% natural aloe vera gel, preservative-free and fragrance-free. Instantly soothes sunburn, hydrates dry skin and doubles as a hair gel. Suitable for all skin types.",
    4.5, 50),
  p("mae-moist-rice",    "Rice Oil-Free Face Moisturizer",   299, "Mamaearth", "Face Serum", IMG.serum, "Rice Water",
    "Toxin-Free ✓",
    "A lightweight, oil-free gel moisturiser with rice water that hydrates combination and oily skin without clogging pores or leaving a greasy residue.",
    4.3, 38),

  // ── Mamaearth — Sunscreen ─────────────────────────────────────────────────
  p("mae-sun-vitc", "Vitamin C Sunscreen SPF 50", 299, "Mamaearth", "Sunscreen", IMG.sunscreen, "SPF 50 PA+++",
    "Toxin-Free ✓",
    "A dual-action sunscreen with SPF 50 PA+++ and Vitamin C that protects against UV damage while actively brightening skin. Non-greasy, suitable for daily wear under makeup.",
    4.5, 35),
  p("mae-sun-aloe", "Aloe Vera Sunscreen SPF 55",  299, "Mamaearth", "Sunscreen", IMG.sunscreen, "SPF 55 PA++++",
    "Toxin-Free ✓",
    "A soothing aloe vera-based sunscreen with the highest PA++++ rating that provides broad-spectrum protection while cooling and hydrating sensitive, sun-exposed skin.",
    4.4, 30),

  // ── Mamaearth — Face Mask ─────────────────────────────────────────────────
  p("mae-mask-ubtan", "Ubtan Face Mask", 299, "Mamaearth", "Face Mask", IMG.faceMask, "Saffron & Turmeric",
    "Toxin-Free ✓",
    "A traditional ubtan mask with saffron, turmeric and chickpea flour that detans, brightens skin and imparts a natural golden glow in just 15 minutes.",
    4.4, 28),
  p("mae-mask-c3",    "C3 Face Mask",    299, "Mamaearth", "Face Mask", IMG.faceMask, "Charcoal, Coffee & Clay",
    "Toxin-Free ✓",
    "A triple-action detox mask with activated charcoal, coffee and kaolin clay that deep-cleanses pores, energises dull skin and controls excess oil for a clear complexion.",
    4.5, 32),

  // ── Mamaearth — Body Care ─────────────────────────────────────────────────
  p("mae-bw-ubtan",  "Ubtan Body Wash",       299, "Mamaearth", "Body Wash",   IMG.maeUbtanWash,   "Turmeric & Saffron",
    "Toxin-Free ✓",
    "A luxury body wash inspired by Indian bridal rituals with turmeric and saffron that cleanses, brightens and imparts a soft golden radiance to the skin.",
    4.4, 36),
  p("mae-bl-vitc",   "Vitamin C Body Lotion", 299, "Mamaearth", "Body Lotion", IMG.maeVitCLotion, "Skin Brightening",
    "Toxin-Free ✓",
    "A fast-absorbing body lotion with Vitamin C that brightens dull skin, fades body tan and provides 48-hour deep hydration for uniformly radiant skin.",
    4.3, 40),
  p("mae-bl-ubtan",  "Ubtan Body Lotion",     299, "Mamaearth", "Body Lotion", IMG.bodyLotion, "Turmeric & Saffron",
    "Toxin-Free ✓",
    "A moisturising body lotion with turmeric and saffron that nourishes, brightens and gives the skin a warm, natural glow while keeping it hydrated all day.",
    4.4, 38),
  p("mae-bb-coco",   "Coco Body Butter",      399, "Mamaearth", "Body Cream",  IMG.bodyButter, "Coffee & Cocoa",
    "Toxin-Free ✓",
    "An indulgent body butter with coffee and cocoa butter that provides intense, long-lasting moisture for dry and rough skin. Melts on contact for silky-smooth results.",
    4.6, 25),
  p("mae-bl-aloe",   "Aloe Vera Body Lotion", 249, "Mamaearth", "Body Lotion", IMG.bodyLotion, "Pure Aloe Vera",
    "Toxin-Free ✓",
    "A gentle, cooling aloe vera body lotion that soothes irritated skin, provides lightweight hydration and is perfect for post-sun care and sensitive skin types.",
    4.2, 45),

  // ── Mamaearth — Hair Care ─────────────────────────────────────────────────
  p("mae-oil-onion",    "Onion Hair Oil",       349, "Mamaearth", "Hair Care", IMG.maeOnionOil,     "Onion & Redensyl",
    "Bestseller",
    "A clinically proven hair growth oil with onion extract and Redensyl that strengthens hair roots, reduces hair fall by up to 80% and promotes new hair growth.",
    4.5, 42),
  p("mae-oil-rosemary", "Rosemary Hair Growth Oil", 349, "Mamaearth", "Hair Care", IMG.hairOil, "Rosemary Extract",
    "New",
    "A plant-powered hair growth oil with rosemary and peppermint that stimulates the scalp, improves blood circulation and is clinically shown to be as effective as minoxidil.",
    4.6, 38),
  p("mae-shp-onion",    "Onion Shampoo",        349, "Mamaearth", "Hair Care", IMG.maeOnionShp,     "Onion & Plant Keratin",
    "Bestseller",
    "A sulphate-free onion shampoo with plant keratin that strengthens each strand from root to tip, reduces breakage and adds brilliant shine to dull, damaged hair.",
    4.4, 40),
  p("mae-shp-teatree",  "Tea Tree Shampoo",     299, "Mamaearth", "Hair Care", IMG.shampoo,     "Tea Tree & Ginger",
    "Toxin-Free ✓",
    "A refreshing anti-dandruff shampoo with tea tree oil and ginger extract that removes dandruff, soothes an itchy scalp and leaves hair clean, fresh and flake-free.",
    4.3, 44),
  p("mae-cond-onion",   "Onion Conditioner",    299, "Mamaearth", "Hair Care", IMG.conditioner, "Hair Fall Control",
    "Toxin-Free ✓",
    "A detangling conditioner with onion extract and plant proteins that softens hair, reduces breakage during combing and seals the cuticle for frizz-free, manageable locks.",
    4.4, 36),
  p("mae-mask-onion",   "Onion Hair Mask",      399, "Mamaearth", "Hair Care", IMG.hairMask,    "Deep Nourishment",
    "Toxin-Free ✓",
    "An intensive weekly hair mask with onion, coconut and argan oils that repairs severely damaged hair, replenishes lost moisture and restores strength and shine.",
    4.5, 28),
  p("mae-ser-onion",    "Onion Hair Serum",     349, "Mamaearth", "Hair Care", IMG.hairSerum,   "Onion & Biotin",
    "Toxin-Free ✓",
    "A lightweight hair serum with onion extract and biotin that controls frizz, adds brilliant shine and provides heat protection up to 230°C for styled hair.",
    4.3, 32),
  p("mae-mask-argan",   "Argan Hair Mask",      399, "Mamaearth", "Hair Care", IMG.hairMask,    "Argan Oil",
    "Toxin-Free ✓",
    "A deep conditioning mask with Moroccan argan oil and shea butter that transforms coarse, frizzy hair into silky, lustrous locks with just one use.",
    4.6, 24),

  // ── Mamaearth — Makeup ────────────────────────────────────────────────────
  p("mae-mkp-kajal",     "Charcoal Kajal",       199, "Mamaearth", "Makeup", IMG.kajal, "Vitamin E & Castor Oil",
    "Toxin-Free ✓",
    "An intense, long-lasting kajal with activated charcoal for deep black pigmentation. Enriched with vitamin E and castor oil, it's safe for the waterline and lasts 12 hours.",
    4.6, 48),
  p("mae-mkp-lipcrayon", "Lip Crayon Pink Burst",249, "Mamaearth", "Makeup", IMG.lip,   "Shea Butter",
    "Toxin-Free ✓",
    "A creamy lip crayon in the perfect everyday pink with shea butter that conditions lips while providing intense, buildable colour with a comfortable, non-drying finish.",
    4.4, 35),
  p("mae-mkp-lipbalm",   "Strawberry Lip Balm",  149, "Mamaearth", "Makeup", IMG.lip,   "Vitamin E",
    "Toxin-Free ✓",
    "A delicious strawberry-flavoured lip balm with SPF 20 and vitamin E that heals dry, chapped lips while providing sun protection and a natural berry tint.",
    4.5, 60),
];

export const featuredProducts: Product[] = [
  products.find((p) => p.id === "twc-vibe-tribe")!,
  products.find((p) => p.id === "mae-ser-vitc")!,
  products.find((p) => p.id === "kim-love-lotion")!,
  products.find((p) => p.id === "mae-oil-onion")!,
  products.find((p) => p.id === "kim-souq-wash")!,
];

import blogRitual from "@/assets/blog-pads-evolution.jpg";
import blogFragrance from "@/assets/blog-planet-health.jpg";
import blogNiacinamide from "@/assets/blog-sleep.jpg";
import blogGifting from "@/assets/blog-cramps.jpg";

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Building a Daily Body Care Ritual",
    excerpt: "A simple morning-to-night routine using lotions, creams, and mists for soft, glowing skin.",
    image: blogRitual,
    slug: "building-a-daily-body-care-ritual",
    author: "Editorial Team",
    date: "Jun 12, 2026",
    readTime: "6 min read",
    sections: [
      { id: "morning", heading: "Morning: cleanse and hydrate", paragraphs: [
        "Start your day with a gentle body wash that respects your skin's natural barrier. Follow with a lightweight lotion that absorbs quickly so you can dress without waiting.",
        "Look for ingredients like niacinamide, glycerin and squalane — they hydrate without feeling heavy, even in humid weather.",
      ]},
      { id: "midday", heading: "Midday: refresh with a body mist", paragraphs: [
        "A few spritzes of a body mist between meetings or after the gym can completely reset how your skin feels. Pick a scent family you genuinely enjoy — citrus for energy, florals for warmth, woody notes for grounding.",
      ]},
      { id: "evening", heading: "Evening: nourish overnight", paragraphs: [
        "Trade your morning lotion for a richer body cream at night. Skin repair peaks during sleep, so a butter-textured cream layered on damp skin locks in maximum moisture.",
        "Pay attention to elbows, knees and heels — they need the extra love.",
      ]},
    ],
  },
  {
    id: "2",
    title: "How to Choose a Signature Fragrance",
    excerpt: "Discover scent families and find the EDP that matches your mood and personality.",
    image: blogFragrance,
    slug: "how-to-choose-a-signature-fragrance",
    author: "Editorial Team",
    date: "May 28, 2026",
    readTime: "5 min read",
    sections: [
      { id: "families", heading: "Understand the four scent families", paragraphs: [
        "Most fragrances fall into floral, woody, oriental or fresh. Knowing which family you gravitate toward narrows hundreds of options into a handful worth sampling.",
      ]},
      { id: "skin-test", heading: "Always test on skin, never on paper", paragraphs: [
        "A scent transforms once it meets your skin's chemistry. Spray on a pulse point and wear it for at least four hours before deciding — the dry-down is what you'll smell like most of the day.",
      ]},
      { id: "occasions", heading: "Match the scent to the occasion", paragraphs: [
        "Lighter, citrusy EDPs suit daytime and the office. Warmer, deeper scents come alive in the evening. Many people keep two — a daily go-to and a special-occasion bottle.",
      ]},
    ],
  },
  {
    id: "3",
    title: "The Science of Niacinamide",
    excerpt: "Why this hero ingredient deserves a spot in your face and body care routine.",
    image: blogNiacinamide,
    slug: "the-science-of-niacinamide",
    author: "Editorial Team",
    date: "May 14, 2026",
    readTime: "7 min read",
    sections: [
      { id: "what", heading: "What is niacinamide?", paragraphs: [
        "Niacinamide is a form of vitamin B3 that supports the skin's natural barrier, regulates oil production and visibly evens skin tone over time.",
      ]},
      { id: "benefits", heading: "Why it works for almost everyone", paragraphs: [
        "Unlike many actives, niacinamide is gentle enough for sensitive skin and pairs well with retinol, vitamin C and acids. A 5% concentration is the sweet spot for most people.",
      ]},
      { id: "how", heading: "How to use it daily", paragraphs: [
        "Apply after cleansing and before heavier creams. Consistency matters more than concentration — results show after 4–8 weeks of daily use.",
      ]},
    ],
  },
  {
    id: "4",
    title: "Gifting Guide: Curated Sets She'll Love",
    excerpt: "From bath duos to fragrance trios, our most-loved sets for every occasion.",
    image: blogGifting,
    slug: "gifting-guide-curated-sets",
    author: "Editorial Team",
    date: "Apr 30, 2026",
    readTime: "4 min read",
    sections: [
      { id: "duos", heading: "Bath and body duos", paragraphs: [
        "Matching shower gel and lotion sets are the easiest way to gift a complete routine. They feel considered without requiring you to guess at preferences.",
      ]},
      { id: "fragrance", heading: "Fragrance sets for explorers", paragraphs: [
        "If the person you're gifting loves trying new scents, a multi-bottle EDP set lets them experiment without committing to a full bottle.",
      ]},
      { id: "wrap", heading: "A note on presentation", paragraphs: [
        "Premium packaging matters. Choose sets that arrive gift-ready so you can skip the wrapping paper without skipping the wow.",
      ]},
    ],
  },
];
