UPDATE public.products SET image_url = '/assets/images/products/mae-sun-aloe.jpg' WHERE name = 'Aloe Vera Sunscreen SPF 55';
UPDATE public.products SET image_url = '/assets/images/products/mae-mask-argan.jpg' WHERE name = 'Argan Hair Mask';
UPDATE public.products SET image_url = '/assets/images/products/around-the-world-body-mist.jpg' WHERE name = 'Around The World Body Mist';
UPDATE public.products SET image_url = '/assets/images/products/around-the-world-clarifying-body-wash.jpg' WHERE name = 'Around The World Clarifying Body Wash';
UPDATE public.products SET image_url = '/assets/images/products/around-the-world-moisturizing-body-wash.jpg' WHERE name = 'Around The World Moisturizing Body Wash';
UPDATE public.products SET image_url = '/assets/images/products/around-the-world-renewing-body-wash.jpg' WHERE name = 'Around The World Renewing Body Wash';
UPDATE public.products SET image_url = '/assets/images/products/twc-razors.jpg' WHERE name = 'Bamboo Razors';
UPDATE public.products SET image_url = '/assets/images/products/mae-mask-c3.jpg' WHERE name = 'C3 Face Mask';
UPDATE public.products SET image_url = '/assets/images/products/mae-bb-coco.jpg' WHERE name = 'Coco Body Butter';
UPDATE public.products SET image_url = '/assets/images/products/herbalist-body-care-duo.jpg' WHERE name = 'Herbalist Body Care Duo';
UPDATE public.products SET image_url = '/assets/images/products/indian-apothecary-body-care-duo.jpg' WHERE name = 'Indian Apothecary Body Care Duo';
UPDATE public.products SET image_url = '/assets/images/products/lip.jpg' WHERE name = 'Lip Crayon Pink Burst';
UPDATE public.products SET image_url = '/assets/images/products/menstrual-cups.jpg' WHERE name = 'Menstrual Cups';
UPDATE public.products SET image_url = '/assets/images/products/mae-moist-rice.jpg' WHERE name = 'Rice Oil-Free Face Moisturizer';
UPDATE public.products SET image_url = '/assets/images/products/mae2-cr-illuminate.jpg' WHERE name = 'Skin Illuminate Face Cream';
UPDATE public.products SET image_url = '/assets/images/products/stand-pee.jpg' WHERE name = 'Stand And Pee Sticks';
UPDATE public.products SET image_url = '/assets/images/products/lip.jpg' WHERE name = 'Strawberry Lip Balm';
UPDATE public.products SET image_url = '/assets/images/products/twc-tampons.jpg' WHERE name = 'Tampons Without Applicator';
UPDATE public.products SET image_url = '/assets/images/products/teen-pad.jpg' WHERE name = 'Teen Pad 240MM';
UPDATE public.products SET image_url = '/assets/images/products/the-gentleman-niacinamide-body-cream.jpg' WHERE name = 'The Gentleman Niacinamide Body Cream';
UPDATE public.products SET image_url = '/assets/images/products/the-gulistan-body-cream.jpg' WHERE name = 'The Gulistan Body Cream 100gm';
UPDATE public.products SET image_url = '/assets/images/products/mae-mask-ubtan.jpg' WHERE name = 'Ubtan Face Mask';
UPDATE public.products SET image_url = '/assets/images/products/under-eye-cream.jpg' WHERE name = 'Under Eye Cream';
UPDATE public.products SET image_url = '/assets/images/products/mae-bl-vitc.jpg' WHERE name = 'Vitamin C Body Lotion';
